name: madrasa_fund_management
description: A lightweight app for managing Madrasa finances

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  pdf: ^3.10.0
  printing: ^5.9.1
  excel: ^2.0.0
  google_sign_in: ^5.4.0
  googleapis: ^9.0.0
  googleapis_auth: ^1.3.0
  url_launcher: ^6.1.7
  flutter_email_sender: ^5.2.0
  whatsapp_unilink: ^2.0.0
  sqflite: ^2.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/